language: csharp
mono:
 - beta

install: 
 - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh
 - dnvm upgrade

script:
 - build_num = $TRAVIS_BUILD_NUMBER
 - build_num=$(printf "%.4d" "$build_num")
 - cd tests
 - dnu restore
 - dnx test
 - cd ../src/Interchange
 - dnu restore
 - dnu pack --configuration Release
 - cd bin/Release
 - nuget push *.nupkg -ApiKey "$API_KEY" -Source "$FEED_URL"