language: csharp

sudo: required
dist: trusty

mono:
 - beta

install: 
 - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet
 - sudo ln -s ~/dotnet/dotnet /usr/local/bin

script:
 - build_num=$TRAVIS_BUILD_NUMBER
 - build_num=$(printf "%.4d" "$build_num")
 - export DNX_BUILD_VERSION=$build_num
 - cd tests
 - dotnet restore
 - dotnet test
 - cd ../src/Interchange
 - dotnet restore
 - dotnet pack --configuration Release
 - cd bin/Release
 - nuget push *.nupkg -ApiKey "$API_KEY" -Source "$FEED_URL"