language: csharp

sudo: required
dist: trusty

mono: beta
dotnet: 1.0.0-preview2-003121

script:
 - build_num=$TRAVIS_BUILD_NUMBER
 - build_num=$(printf "%.4d" "$build_num")
 - export DOTNET_BUILD_VERSION=$build_num
 - dotnet restore
 - cd tests
 - dotnet test
 - cd ../src/Interchange
 - dotnet pack --configuration Release
 - cd bin/Release
 - nuget push *.nupkg -ApiKey "$API_KEY" -Source "$FEED_URL"